### PR TITLE
Fix read-only var

### PR DESCRIPTION
**Pull request by kdawgwilk**
This addresses #7

### CODE REVIEW

**Comment by jaimeagudo** [comment]
lets merge it please :)

**Comment by kdawgwilk** [comment]
Also fixes a Yellowbox warning related to refs

**Comment by ammichael** [comment]
How is this still open 1 month later?! I had to manually change it to the lib works

**Comment by ammichael** [comment]
Hey @yogevbd, sorry the inconvenience, but can you please accept the merge? Everytime someone in my team needs to reinstall the packages, they are greeted with an error.

**Pull request merged**
